In [35]:
import pandas as pd
import os
import glob

In [37]:
trades = pd.read_csv('trades0720.csv', sep=';')

In [38]:
trades.dtypes

TRADEDATE    object
TRADETIME    object
SECID        object
BOARDID      object
PRICE        object
VOLCUR        int64
INVCURVOL    object
BUYSELL      object
TRADENO       int64
dtype: object

In [39]:
trades.head(10)

,TRADEDATE,TRADETIME,SECID,BOARDID,PRICE,VOLCUR,INVCURVOL,BUYSELL,TRADENO
0,02.07.2020,9:50:57,USDRUB_WAP0,WAPS,"70,5198",237000,"16713192,6",B,243306006
1,02.07.2020,9:58:46,USDRUB_WAP0,WAPS,"70,5198",213000,"15020717,4",S,243306034
2,02.07.2020,10:00:00,USD000000TOD,CETS,"70,9825",50000,3549125,S,243306036
3,02.07.2020,10:00:00,USD000UTSTOM,CETS,71,5000,355000,S,243306037
4,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,615",100000,7061500,B,243306038
5,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,62",100000,7062000,B,243306039
6,02.07.2020,10:00:00,CNYRUB_TOM,CETS,"10,008",3000000,30024000,B,243306040
7,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,8025",100000,7080250,S,243306041
8,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,8",186000,13168800,S,243306042
9,02.07.2020,10:00:00,USD000000TOD,CETS,"70,785",50000,3539250,S,243306043

#### Filter by SECID and BOARDID

In [40]:
trades_secid = trades['SECID']=='USD000UTSTOM'
trades_boardid = trades['BOARDID']=='CETS'
uts = trades[trades_boardid & trades_secid]

In [41]:
uts.head(10)

,TRADEDATE,TRADETIME,SECID,BOARDID,PRICE,VOLCUR,INVCURVOL,BUYSELL,TRADENO
3,02.07.2020,10:00:00,USD000UTSTOM,CETS,71,5000,355000,S,243306037
4,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,615",100000,7061500,B,243306038
5,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,62",100000,7062000,B,243306039
7,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,8025",100000,7080250,S,243306041
8,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,8",186000,13168800,S,243306042
15,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,8",50000,3540000,S,243306049
20,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,8",618000,43754400,S,243306054
22,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,7975",49000,"3469077,5",B,243306056
23,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,655",95000,6712225,S,243306057
25,02.07.2020,10:00:00,USD000UTSTOM,CETS,"70,655",5000,353275,S,243306059